language: bash
sudo: required
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - secure: "KuBfWClkLm0SBUGaoPHW5zg8xrYy4c8qUHVuz0EEmCwxr1xKkUWkQUyyg27EQjw7HeVU6Rzg0I4PXV8tsX0aWujhDZm5ioHFuy5qDffVr8Cq7FaXxRnlVTxCPfF+6RYKYj2WU87Cvb3nuKe6y/SIj0WvWlmJKORYHNyPcB89S//9xrg26CNiuxRPaGvQVqlcHOHyQb1nrTJ0Vb0ZtyZIoqP8AQYmHSmKz2/Q0TE2FOUkiDDCnxVeKl19Go85DZIDvhQZqOJ4MAdLaqqm2OOP9Xykeg9qmhQ9XK3enkuK6nyxthFKgK2WcR2h52gICtQoVEei7TOAZZRXkyTVzxE15be303PBCvZU2UWHPzkvAtd0nwFPfCcRunMW6w1XWyiC2g+JOUHcWrhZG79noyTuUWAwwXZAXG2oi8yVI8bpKaHyNpoSj/2yCDm9nYPPOV6HsVQOAI9wjwwDjkdr4AG81AK5VjCcEbpYtmF2wU8Zi01YSMoAFu90Zy/Ci1avNfOTAvwwtFfdB2Vh9w7oYt4zdJJQqcuT7QaFV77+jm3xIh7bn6g0wKsBALFO0u/tw5GTrYQMUKW4hr0ODB11eIoRgIOsNr+oWta2EKVG+NSy+C7XiDlWknKclKiJgCMK7sWz+8NMNnej0dHNTvZpO80dmW0WzkeWZqgqKMc/liqSFl0="
  - secure: "KNKc72qckJRJxSLzxPEWDGKUSIlUvoOWOdtQopoie9MGv9VUjvzL5kwqOkNkYN5ONZU8RIzVRHywf787zC/qjdYoAOP4ZlDOTHszmIRj39uBAqu3qfri+KAqqG/mkt5xeBa0qNJHphmqEDofsplaDh9xkssvWvbABl8gJ8PyOzTwM5SR2lFW/kHzwyspxhj/l6tjZpYbOQeXQllBabRRzI4j2BRQbz+12cMM6doGR29V3yuGmjbSU5uXful5tSlKLfYqQ4Rf7g00mirLO3I2fKuRFZAqIRNpbV6dLIpSQc6xRnWvGQ2Rpkec3Y9O3dXMwVZyR2KaLHApg9VBDhaRy3H81ZJggVNlUYHKyS83E8oGf42BV9U5UPmoT5x8IVK3oy4zT63z6l5nLyGvf31DH/cKYanF1e9QwxXBPp18de8iJjKsEk76THxKpx8aZIbaniu+TLvBhBT+wvayL/FSqjGp6HS6W6wD8hFod7b9ia4AiTSj7haCAIsK4VouRtIA7LhZTvgABUnhzgeG1ASxYu/pMBj3jIIBib1+G6qfWVRU/Z/Htwm0d/viSncIuSOUb4CbZjgHZOcv5vPrr/IdSsv3dTzebtrDE4OW/iHnzr06yqyPA7TUYcP7QYlXeCpYChYKYUEuN/maaVF31MOGFX3jsQRdApBimcA1KpH3MZQ="
services:
- docker
install:
- curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
- bash $HOME/bin/travis_ci_operator.sh init
- travis_ci_operator.sh docker-login
- bash .travis.sh install
script:
- bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = "false"
